[project]
name = 'bitcoin-faces-contract'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'
requirements = [
    { contract_id = 'SP2PABAF9FTAJYNFZH93XENAJ8FVY99RRM50D2JG9.nft-trait' }
]

[repl.remote_data]
enabled = true
api_url = 'https://api.hiro.so'
[contracts.bitcoin-faces-nft]
path = 'contracts/bitcoin-faces-nft.clar'
clarity_version = 4
epoch = 'latest'
[repl.analysis]
passes = [
    'call_checker',
    'check_checker',
]

[repl.analysis.lints]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

